AnimalShelter/Models/Animal.cs
namespace AnimalShelter.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Type { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public string AdmittanceDate { get; set; }
    public string Breed { get; set; }
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public DbSet<Animal> Animals { get; set; }

    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;
using System;
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;

    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public ActionResult Create(Animal animal)
    {
        _db.Animals.Add(animal);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
    Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
    Console.WriteLine(thisAnimal);
    return View(thisAnimal);
    }

    public ActionResult Edit(int id)
    {
      var thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

    [HttpPost]
    public ActionResult Edit(Animal animal)
    {
      _db.Entry(animal).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      _db.Animals.Remove(thisAnimal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }


    }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4>Add a new animal</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type)
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Gender)
  @Html.TextBoxFor(model => model.Gender)
  @Html.LabelFor(model => model.AdmittanceDate)
  @Html.TextBoxFor(model => model.AdmittanceDate)
  @Html.LabelFor(model => model.Breed)
  @Html.TextBoxFor(model => model.Breed)
  <input type="submit" value="Add new animal" />
}
<p>@Html.ActionLink("Show all animals", "Index")</p>

AnimalShelter/Views/Animals/Delete.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Are you sure you want to delete this animal?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

AnimalShelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal


<h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)</h3>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Gender): @Html.DisplayFor(model => model.Gender)</h3>
<h3>@Html.DisplayNameFor(model => model.AdmittanceDate): @Html.DisplayFor(model => model.AdmittanceDate)</h3>
<h3>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)</h3>


<p>@Html.ActionLink("Edit Animal", "Edit", new { id = Model.AnimalId })</p>

<p>@Html.ActionLink("Delete Animal", "Delete", new { id = Model.AnimalId })</p>

<p>@Html.ActionLink("Back to list", "Index")</p>

    

AnimalShelter/Views/Animals/Edit.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Edit</h2>

<h4>Edit this animal: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.AnimalId)

    @Html.LabelFor(model => model.Type)
    @Html.EditorFor(model => model.Type)
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)
    @Html.LabelFor(model => model.Gender)
    @Html.EditorFor(model => model.Gender)
    @Html.LabelFor(model => model.AdmittanceDate)
    @Html.EditorFor(model => model.AdmittanceDate)
    @Html.LabelFor(model => model.Breed)
    @Html.EditorFor(model => model.Breed)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;
@model List<AnimalShelter.Models.Animal>;

<h1>Animals</h1>

<ul>
  @foreach(Animal Animal in Model)
  {
    <li>@Html.ActionLink($"{Animal.Name}", "Details", new { id = Animal.AnimalId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new Animal", "Create")</p>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Animal Shelter!</h1>
<p>@Html.ActionLink("See all animals", "Index", "Animals")</p> 

AnimalShelter/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My To-Do List!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>